Update tether

diff --git a/tether b/tether
--- a/tether
+++ b/tether
@@ -2,7 +2,8 @@
 echo "Ligando modulos"
 modprobe mii ; modprobe usbnet
 echo "Modulos ligados"
-echo "Conectando"
+echo "Connecting"
 dhclient usb0
-ping -c4 8.8.8.8 || echo "Deu errado"
+ping -c4 8.8.8.8 || echo "Error 0000, cant connect!" && exit
+echo "Connected"
 exit
